spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securecap
    username: postgres
    password: 2373
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
      continue-on-error: false

